// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PostagensApi.Models;

public partial class Comment
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long PostId { get; set; }

    public string Comment1 { get; set; }


    [JsonIgnore]
    public virtual Post Post { get; set; }

    [JsonIgnore]
    public virtual User User { get; set; }
}