// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PostagensApi.Models;

public partial class db_SocialContext : DbContext
{
    public db_SocialContext(DbContextOptions<db_SocialContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Like> Likes { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Like>(entity =>
        {
            entity.HasIndex(e => e.IdPost, "IX_Likes_IdPost");

            entity.HasIndex(e => e.IdUsuario, "IX_Likes_IdUsuario");

            entity.HasOne(d => d.IdPostNavigation).WithMany(p => p.Likes).HasForeignKey(d => d.IdPost);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Likes)
                .HasForeignKey(d => d.IdUsuario);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.ToTable("Post");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasDefaultValueSql("(N'')");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasDefaultValueSql("(N'')");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasDefaultValueSql("(N'')");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasDefaultValueSql("(N'')");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasDefaultValueSql("(N'')");

            entity.HasMany(u => u.Posts)
               .WithOne(p => p.User)
               .HasForeignKey(p => p.AuthorId)
               .OnDelete(DeleteBehavior.SetNull);

            entity.HasMany(u => u.Likes)
             .WithOne(p => p.IdUsuarioNavigation)
             .HasForeignKey(p => p.IdUsuario)
             .OnDelete(DeleteBehavior.SetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}