// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PostagensApi.Models;

public partial class Like
{
    public int Id { get; set; }

    public long IdUsuario { get; set; }

    public long IdPost { get; set; }

    public virtual Post IdPostNavigation { get; set; }

    public virtual User IdUsuarioNavigation { get; set; }
}