// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PostagensApi.Models;

public partial class Post
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int AuthorId { get; set; }

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();
}