// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PostagensApi.Models;

public partial class Post
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public long AuthorId { get; set; }

    [JsonIgnore]
    public User User { get; set; } 

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();
}